version: '3'

services:
  postgres:
    image: postgres:16.2-alpine3.19
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "go_clean_architecture"
      POSTGRES_USER: "username_go"
      POSTGRES_PASSWORD: "password_go"