# app:
#   port: 8080

# postgres:
#   host: localhost
#   port: 5432
#   username: root
#   password: secret
#   dbname: postgres
#   sslmode: false

app:
  port: 8080
postgres:
  host: localhost
  port: 5432
  username: "username_go"
  password: "password_go"
  dbname: go_clean_architecture
  sslmode: false
server:
  expire_token: 15m
  host_key: "xxxxxxx"